// frontend/src/components/ui/ConfirmDialog.tsx
import { Dialog } from './Dialog';
import { Button } from './Button';

export interface ConfirmDialogProps {
  open: boolean;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  onConfirm: () => void;
  onCancel: () => void;
  variant?: 'danger' | 'default';
}

export function ConfirmDialog({
  open,
  title,
  message,
  confirmText = '确认',
  cancelText = '取消',
  onConfirm,
  onCancel,
  variant = 'default',
}: ConfirmDialogProps) {
  return (
    <Dialog
      open={open}
      onClose={onCancel}
      title={title}
      footer={
        <>
          <Button variant="secondary" onClick={onCancel}>
            {cancelText}
          </Button>
          <Button
            variant={variant === 'danger' ? 'danger' : 'primary'}
            onClick={onConfirm}
          >
            {confirmText}
          </Button>
        </>
      }
    >
      <span style={{ color: '#424245' }}>{message}</span>
    </Dialog>
  );
}

// frontend/src/components/ui/ConfirmDialog.vue
<script setup lang="ts">
import Dialog from './Dialog.vue'
import Button from './Button.vue'

withDefaults(
  defineProps<{
    open: boolean
    title: string
    message: string
    confirmText?: string
    cancelText?: string
    variant?: 'danger' | 'default'
  }>(),
  { confirmText: '确认', cancelText: '取消', variant: 'default' },
)

const emit = defineEmits<{ confirm: []; cancel: [] }>()
</script>

<template>
  <Dialog :open="open" :title="title" @close="emit('cancel')">
    <span style="color: #424245">{{ message }}</span>
    <template #footer>
      <Button variant="secondary" @click="emit('cancel')">{{ cancelText }}</Button>
      <Button :variant="variant === 'danger' ? 'danger' : 'primary'" @click="emit('confirm')">
        {{ confirmText }}
      </Button>
    </template>
  </Dialog>
</template>
