// frontend/src/components/ui/Dialog.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'

const props = defineProps<{
  open: boolean
  title?: string
}>()

const emit = defineEmits<{ close: [] }>()

function handleEsc(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.open) emit('close')
}
onMounted(() => document.addEventListener('keydown', handleEsc))
onUnmounted(() => document.removeEventListener('keydown', handleEsc))
</script>

<template>
  <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center">
    <div class="absolute inset-0 bg-black/40" @click="emit('close')" />
    <div
      class="relative z-10 flex max-h-[90vh] min-w-[320px] max-w-[90vw] flex-col rounded-[4px] border bg-[#fdfcfc]"
      style="border-color: rgba(15, 0, 0, 0.12)"
    >
      <div
        v-if="title || $slots.title"
        class="flex shrink-0 items-center justify-between px-4 py-3"
        style="border-bottom: 1px solid rgba(15, 0, 0, 0.12)"
      >
        <div class="text-sm font-medium text-[#201d1d]"><slot name="title">{{ title }}</slot></div>
        <button
          type="button"
          class="text-[#646262] hover:text-[#201d1d] transition-colors cursor-pointer"
          @click="emit('close')"
        >
          ✕
        </button>
      </div>
      <div class="min-h-0 flex-1 overflow-auto px-4 py-3 text-sm text-[#201d1d]"><slot /></div>
      <div
        v-if="$slots.footer"
        class="flex shrink-0 items-center justify-end gap-2 px-4 py-3"
        style="border-top: 1px solid rgba(15, 0, 0, 0.12)"
      >
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>

// frontend/src/components/ui/Dialog.tsx
import React, { useEffect } from 'react';
import { cn } from '@/lib/utils';

export interface DialogProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'title'> {
  open: boolean;
  onClose: () => void;
  title?: React.ReactNode;
  footer?: React.ReactNode;
}

export const Dialog = React.forwardRef<HTMLDivElement, DialogProps>(
  ({ open, onClose, title, footer, children, className, ...props }, ref) => {
    useEffect(() => {
      if (!open) return;
      const handleEsc = (e: KeyboardEvent) => {
        if (e.key === 'Escape') onClose();
      };
      document.addEventListener('keydown', handleEsc);
      return () => document.removeEventListener('keydown', handleEsc);
    }, [open, onClose]);

    if (!open) return null;

    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center">
        <div
          className="absolute inset-0 bg-black/40"
          onClick={onClose}
        />
        <div
          ref={ref}
          className={cn(
            'relative z-10 min-w-[320px] max-w-[560px] rounded-[4px] border bg-[#fdfcfc]',
            className
          )}
          style={{ borderColor: 'rgba(15, 0, 0, 0.12)' }}
          {...props}
        >
          {title && (
            <div
              className="flex items-center justify-between px-4 py-3"
              style={{ borderBottom: '1px solid rgba(15, 0, 0, 0.12)' }}
            >
              <div className="text-sm font-medium text-[#201d1d]">{title}</div>
              <button
                type="button"
                className="text-[#646262] hover:text-[#201d1d] transition-colors cursor-pointer"
                onClick={onClose}
              >
                ✕
              </button>
            </div>
          )}
          <div className="px-4 py-3 text-sm text-[#201d1d]">{children}</div>
          {footer && (
            <div
              className="flex items-center justify-end gap-2 px-4 py-3"
              style={{ borderTop: '1px solid rgba(15, 0, 0, 0.12)' }}
            >
              {footer}
            </div>
          )}
        </div>
      </div>
    );
  }
);
Dialog.displayName = 'Dialog';
