// frontend/src/components/ui/Tooltip.vue
<script setup lang="ts">
import { onUnmounted, ref } from 'vue'

export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right'

const props = withDefaults(
  defineProps<{
    content: string
    placement?: TooltipPlacement
    delay?: number
  }>(),
  { placement: 'top', delay: 200 },
)

const placementStyles: Record<TooltipPlacement, string> = {
  top: 'bottom-full left-1/2 -translate-x-1/2 mb-1.5',
  bottom: 'top-full left-1/2 -translate-x-1/2 mt-1.5',
  left: 'right-full top-1/2 -translate-y-1/2 mr-1.5',
  right: 'left-full top-1/2 -translate-y-1/2 ml-1.5',
}

const visible = ref(false)
let timeout: ReturnType<typeof setTimeout> | null = null

function handleMouseEnter() {
  timeout = setTimeout(() => (visible.value = true), props.delay)
}
function handleMouseLeave() {
  if (timeout) {
    clearTimeout(timeout)
    timeout = null
  }
  visible.value = false
}
onUnmounted(() => {
  if (timeout) clearTimeout(timeout)
})
</script>

<template>
  <div class="relative inline-flex" @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave">
    <slot />
    <div
      v-if="visible"
      class="pointer-events-none absolute z-50 whitespace-nowrap rounded-[4px] border bg-[#201d1d] px-2 py-1 text-xs text-[#fdfcfc]"
      :class="placementStyles[placement]"
      style="border-color: rgba(15, 0, 0, 0.12)"
    >
      <slot name="content">{{ content }}</slot>
    </div>
  </div>
</template>

// frontend/src/components/ui/Tooltip.tsx
import React, { useState, useRef } from 'react';
import { cn } from '@/lib/utils';

export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

export interface TooltipProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'content'> {
  content: React.ReactNode;
  placement?: TooltipPlacement;
  delay?: number;
}

const placementStyles: Record<TooltipPlacement, string> = {
  top: 'bottom-full left-1/2 -translate-x-1/2 mb-1.5',
  bottom: 'top-full left-1/2 -translate-x-1/2 mt-1.5',
  left: 'right-full top-1/2 -translate-y-1/2 mr-1.5',
  right: 'left-full top-1/2 -translate-y-1/2 ml-1.5',
};

export const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
  ({ content, placement = 'top', delay = 200, children, className, ...props }, ref) => {
    const [visible, setVisible] = useState(false);
    const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    const handleMouseEnter = () => {
      timeoutRef.current = setTimeout(() => setVisible(true), delay);
    };

    const handleMouseLeave = () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
      setVisible(false);
    };

    return (
      <div
        ref={ref}
        className={cn('relative inline-flex', className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        {children}
        {visible && (
          <div
            className={cn(
              'pointer-events-none absolute z-50 whitespace-nowrap rounded-[4px] border bg-[#201d1d] px-2 py-1 text-xs text-[#fdfcfc]',
              placementStyles[placement]
            )}
            style={{ borderColor: 'rgba(15, 0, 0, 0.12)' }}
          >
            {content}
          </div>
        )}
      </div>
    );
  }
);
Tooltip.displayName = 'Tooltip';
